
export const ErrorCodes = {
  NETWORK_ERROR: "NETWORK_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
